import type { Lang } from "../lang";
import { defaultLang, langPath } from "../lang";
import { applyLocaleContactToHtml } from "../contact";

/** Chrome + long-form prose for the Legal section (privacy + impressum). */
export interface LegalStrings {
  common: { home: string; legal: string; lastUpdated: string };
  privacy: {
    metaTitle: string;
    lastUpdatedDate: string;
    ctaTitle: string;
    ctaSubtitle: string;
    /** Full HTML body rendered inside <LegalProse> via set:html. */
    body: string;
  };
  impressum: {
    metaTitle: string;
    body: string;
  };
  cookies: {
    metaTitle: string;
    lastUpdatedDate: string;
    ctaTitle: string;
    ctaSubtitle: string;
    body: string;
  };
}

const en: LegalStrings = {
  common: { home: "Home", legal: "Legal", lastUpdated: "Last updated:" },
  privacy: {
    metaTitle: "Privacy policy | IoT Fabrikken",
    lastUpdatedDate: "22 May 2026",
    ctaTitle: "Questions about your data?",
    ctaSubtitle:
      "Contact us, we respond on working days and can point you to the right person for GDPR or product-specific requests.",
    body: `
    <p>This Privacy Policy describes how IoT Fabrikken ApS ("<strong>IoT Fabrikken</strong>", "<strong>we</strong>", "<strong>us</strong>" or "<strong>our</strong>") collects, uses and shares personal data when you use our website, the RoomAlyzer platform and related services (together, the "<strong>Service</strong>"). It also explains your privacy rights and how applicable law protects you.</p>
    <p>We use personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy. Where we process personal data on behalf of a customer (for example sensor readings and building data in RoomAlyzer), we act as a <strong>data processor</strong> under the customer's instructions; the customer's privacy notice and data processing agreement apply to that processing.</p>
    <h2>Interpretation and definitions</h2>
    <h3>Interpretation</h3>
    <p>Words with an initial capital letter have the meanings set out below. The same meaning applies whether they appear in singular or plural.</p>
    <h3>Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
      <li><strong>Account</strong> means a unique account created for you to access parts of the Service.</li>
      <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for directors or other managing authority.</li>
      <li><strong>Application</strong> means the RoomAlyzer software provided by the Company, including the web application at app.roomalyzer.com and related mobile or integration interfaces.</li>
      <li><strong>Company</strong> (referred to as "the Company", "We", "Us" or "Our") means IoT Fabrikken ApS, Brønsager 1, 4000 Roskilde, Denmark (CVR 39 11 03 93).</li>
      <li><strong>Country</strong> means Denmark.</li>
      <li><strong>Device</strong> means any device that can access the Service, such as a computer, mobile phone or tablet.</li>
      <li><strong>Personal Data</strong> means any information relating to an identified or identifiable natural person.</li>
      <li><strong>Service</strong> means the website iot-fabrikken.com (and related domains), the Application, customer support portals, demo and contact flows, newsletters and any other services we operate that link to this policy.</li>
      <li><strong>Service Provider</strong> means a natural or legal person who processes data on behalf of the Company to facilitate the Service, provide the Service on our behalf, perform services related to the Service or help us analyse how the Service is used.</li>
      <li><strong>Usage Data</strong> means data collected automatically, either generated by use of the Service or from the Service infrastructure itself (for example, duration of a page visit or API request metadata).</li>
      <li><strong>You</strong> means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>
    <h2>Collecting and using your personal data</h2>
    <h3>Personal data</h3>
    <p>While using our Service, we may ask you to provide personal data that can be used to contact or identify you. This may include, but is not limited to:</p>
    <ul>
      <li>Email address</li>
      <li>First and last name</li>
      <li>Phone number</li>
      <li>Company or organisation name and job title</li>
      <li>Address, city, region and postal code (where relevant for orders or contracts)</li>
      <li>Account credentials and profile preferences</li>
      <li>Content of messages you send us (support, sales, demo requests)</li>
      <li>Usage Data</li>
    </ul>
    <h3>Usage data</h3>
    <p>Usage Data is collected automatically when you use the Service.</p>
    <p>Usage Data may include your Device's Internet Protocol address (IP address), browser type and version, the pages you visit, the time and date of your visit, time spent on those pages, unique device identifiers and other diagnostic data.</p>
    <p>When you access the Service through a mobile device, we may collect information such as the type of mobile device, unique device ID, IP address, mobile operating system, mobile browser type and other diagnostic data.</p>
    <p>We may also collect information your browser sends whenever you visit our website or when you access the Service through a mobile device. For cookies and similar technologies, see our <a href="/en/legal/cookies/">Cookie policy</a>.</p>
    <h3>How we use your personal data</h3>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
      <li><strong>To provide and maintain our Service</strong>, including monitoring usage and operating the Application.</li>
      <li><strong>To manage your Account</strong> and give you access to functionality available to registered users.</li>
      <li><strong>For the performance of a contract</strong> relating to products or services you have purchased or any other contract with us through the Service.</li>
      <li><strong>To contact you</strong> by email, telephone, SMS or other electronic communication regarding updates, security notices, support or information about functionalities, products or contracted services, where necessary or reasonable.</li>
      <li><strong>To provide news and offers</strong> about goods, services and events similar to those you have purchased or enquired about, unless you have opted out.</li>
      <li><strong>To manage your requests</strong> to us (sales, support, demos, careers).</li>
      <li><strong>For business transfers</strong> such as a merger, divestiture, restructuring, reorganisation, dissolution or sale of assets, where Personal Data held about Service users may be among the assets transferred.</li>
      <li><strong>For other purposes</strong> such as data analysis, identifying usage trends, measuring promotional effectiveness and improving our Service, products, services, marketing and your experience.</li>
    </ul>
    <h3>Legal bases (EEA and UK)</h3>
    <p>Where the General Data Protection Regulation (GDPR) or UK GDPR applies, we rely on one or more of the following legal bases: performance of a contract, legitimate interests (for example operating and securing the Service, B2B marketing to existing customers), compliance with a legal obligation, and consent where required (for example certain cookies or marketing sign-ups). You may withdraw consent at any time without affecting the lawfulness of processing before withdrawal.</p>
    <h3>Sharing your personal data</h3>
    <p>We may share your personal data in the following situations:</p>
    <ul>
      <li><strong>With Service Providers</strong> who assist us in operating the Service, hosting, analytics, email delivery, CRM, payment processing or customer support, subject to appropriate contractual safeguards.</li>
      <li><strong>For business transfers</strong> in connection with, or during negotiations of, any merger, sale of Company assets, financing or acquisition.</li>
      <li><strong>With Affiliates</strong>, requiring them to honour this Privacy Policy.</li>
      <li><strong>With business partners</strong> to offer certain products, services or promotions, where you have chosen to participate.</li>
      <li><strong>With other users</strong> when you share personal data or interact in public areas of the Service, where such information may be visible to others.</li>
      <li><strong>With your consent</strong> for any other purpose you have agreed to.</li>
      <li><strong>With authorities</strong> where required by law or to protect rights, safety and security as described below.</li>
    </ul>
    <p>A current list of subprocessors used for RoomAlyzer customer data is available to customers under our <a href="/en/legal/terms/">Terms and data processing agreement</a>.</p>
    <h2>Retention of your personal data</h2>
    <p>We retain Personal Data only for as long as necessary for the purposes set out in this Privacy Policy, including to comply with legal obligations, resolve disputes and enforce agreements.</p>
    <p>Usage Data is generally retained for a shorter period, except where used to strengthen security or improve functionality, or where we are legally required to retain it longer.</p>
    <h2>Transfer of your personal data</h2>
    <p>Your information, including Personal Data, is processed at the Company's offices and in other places where parties involved in processing are located. Data may be transferred to (and maintained on) systems outside your country where data protection laws may differ.</p>
    <p>For customer data in RoomAlyzer, we offer <strong>EU data residency by default</strong>. Where transfers outside the European Economic Area occur, we use appropriate safeguards such as Standard Contractual Clauses or equivalent mechanisms, unless an adequacy decision applies.</p>
    <p>Your consent to this Privacy Policy followed by your submission of information represents your agreement to such transfer where applicable. We take steps reasonably necessary to ensure your data is treated securely and in accordance with this Privacy Policy.</p>
    <h2>Disclosure of your personal data</h2>
    <h3>Business transactions</h3>
    <p>If the Company is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different privacy policy.</p>
    <h3>Law enforcement and other legal requirements</h3>
    <p>Under certain circumstances, the Company may be required to disclose your Personal Data if required by law or in response to valid requests by public authorities (for example a court or government agency). We may disclose Personal Data where we believe in good faith that disclosure is necessary to:</p>
    <ul>
      <li>Comply with a legal obligation</li>
      <li>Protect and defend the rights or property of the Company</li>
      <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
      <li>Protect the personal safety of users of the Service or the public</li>
      <li>Protect against legal liability</li>
    </ul>
    <h2>Security of your personal data</h2>
    <p>The security of your Personal Data is important to us. We use commercially acceptable technical and organisational measures, including encryption in transit and at rest for the Application, access controls and regular security testing. No method of transmission over the Internet or electronic storage is 100% secure; we cannot guarantee absolute security. Further detail is in our <a href="/en/legal/security/">Security</a> page and customer documentation.</p>
    <h2>Your privacy rights</h2>
    <p>Depending on where you live, you may have rights to access, rectify, erase, restrict or object to processing, data portability and to lodge a complaint with a supervisory authority. If you are an end user of a customer's RoomAlyzer deployment, please contact that customer first; we assist our customers in responding to data subject requests as processor.</p>
    <p>To exercise rights relating to data we control directly (for example website accounts, marketing or sales enquiries), contact us using the details below. We may need to verify your identity before responding.</p>
    <h2>Children's privacy</h2>
    <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under 13. If you are a parent or guardian and believe your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under 13 without verification of parental consent, we take steps to remove that information from our servers.</p>
    <p>Where we rely on consent as a legal basis and your country requires consent from a parent, we may require parental consent before we collect and use that information.</p>
    <h2>Links to other websites</h2>
    <p>Our Service may contain links to websites not operated by us. If you click a third-party link, you will be directed to that third party's site. We strongly advise you to review the privacy policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of third-party sites or services.</p>
    <h2>Changes to this privacy policy</h2>
    <p>We may update this Privacy Policy from time to time. We will notify you of material changes by posting the new Privacy Policy on this page and updating the "Last updated" date. Where appropriate, we may also notify you by email or through a prominent notice in the Service before changes take effect.</p>
    <p>You are advised to review this Privacy Policy periodically. Changes are effective when posted on this page.</p>
    <h2>Contact us</h2>
    <p>If you have questions about this Privacy Policy or our use of your personal data, contact us:</p>
    <ul>
      <li><strong>Email:</strong> <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a> (general and privacy enquiries)</li>
      <li><strong>Product support:</strong> <a href="mailto:support@iot-fabrikken.com">support@iot-fabrikken.com</a></li>
      <li><strong>Phone:</strong> <a href="tel:+4571718090">+45 71 71 80 90</a></li>
      <li><strong>Post:</strong> IoT Fabrikken ApS, Brønsager 1, 4000 Roskilde, Denmark</li>
    </ul>
    `,
  },
  cookies: {
    metaTitle: "Cookie policy | IoT Fabrikken",
    lastUpdatedDate: "7 July 2026",
    ctaTitle: "Questions about cookies or tracking?",
    ctaSubtitle:
      "Contact us if you need help changing your preferences or want more detail about how we measure campaigns.",
    body: `
    <p>This Cookie policy explains how IoT Fabrikken ApS ("<strong>we</strong>", "<strong>us</strong>") uses cookies and similar technologies on iot-fabrikken.com (the "<strong>website</strong>"). It should be read together with our <a href="/en/legal/privacy/">Privacy policy</a>.</p>
    <h2>What are cookies?</h2>
    <p>Cookies are small text files stored on your device when you visit a website. Similar technologies include local storage (used to remember your cookie choice) and session storage (used for short-lived form attribution during a visit).</p>
    <h2>How we use cookies</h2>
    <p>We group cookies into three categories. You can accept or reject optional categories via the cookie banner or the "Cookie settings" control shown after you have made a choice.</p>
    <h3>Necessary</h3>
    <p>These are required for the website to remember your cookie preferences. They do not track you across sites.</p>
    <ul>
      <li><strong>Consent preference</strong> — stores your analytics/marketing choice (local storage, up to 12 months).</li>
    </ul>
    <h3>Analytics (optional)</h3>
    <p>Help us understand how visitors use the website so we can improve content and measure organic performance. Loaded only if you consent. Provided via Google Tag Manager, Google Analytics 4 (GA4), and Microsoft Clarity (heatmaps and session recordings).</p>
    <ul>
      <li><strong>_ga, _ga_*</strong> — distinguishes users and sessions (Google Analytics, up to 24 months).</li>
      <li><strong>_gid</strong> — distinguishes users (Google Analytics, 24 hours).</li>
      <li><strong>_clck, _clsk, CLID, ANONCHK, MR, MUID, SM</strong> — Clarity session and heatmap identifiers (Microsoft, typically up to 1 year; session replay is sampled).</li>
    </ul>
    <h3>Marketing (optional)</h3>
    <p>Measure Google Ads campaigns, attribute leads to ads and support remarketing where permitted. Loaded only if you consent.</p>
    <ul>
      <li><strong>_gcl_*</strong> — Google Ads conversion linker and click identifiers (typically 90 days).</li>
    </ul>
    <h2>Legal basis</h2>
    <p>Necessary storage is based on our legitimate interest in operating the website. Analytics and marketing cookies are set only after you give consent via the banner. You can withdraw consent at any time using "Cookie settings" on any page.</p>
    <h2>Managing cookies</h2>
    <p>Use the cookie banner when you first visit, or click <strong>Cookie settings</strong> (bottom-left) to change your choice later. You can also block or delete cookies in your browser settings; some site features may still work, but optional measurement will stop.</p>
    <h2>Updates</h2>
    <p>We may update this policy when we add or remove tools. The "Last updated" date at the top of this page will change accordingly.</p>
    <h2>Contact</h2>
    <p>Questions about cookies: <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a>.</p>
    `,
  },
  impressum: {
    metaTitle: "Impressum | IoT Fabrikken",
    body: `
    <h3>Company details</h3>
    <p><strong>IoT Fabrikken ApS</strong><br />Brønsager 1<br />4000 Roskilde<br />Denmark</p>
    <h3>Represented by</h3>
    <p>Jon Wichmann (CEO / Partner)<br />Mikkel Fischer (Partner)</p>
    <h3>Contact</h3>
    <ul>
      <li><strong>Phone:</strong> <a href="tel:+4571718090">+45 71 71 80 90</a></li>
      <li><strong>Email:</strong> <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a></li>
      <li><strong>Website:</strong> <a href="https://www.iot-fabrikken.com/">www.iot-fabrikken.com</a></li>
    </ul>
    <h3>Register entry</h3>
    <p>Registered in the Danish Business Authority (<em>Det Centrale Virksomhedsregister</em>).</p>
    <p><strong>CVR number:</strong> 39110393</p>
    `,
  },
};

type LegalDictionary = Omit<LegalStrings, "impressum"> & { impressum?: LegalStrings["impressum"] };

const da: LegalDictionary = {
  common: { home: "Hjem", legal: "Juridisk", lastUpdated: "Senest opdateret:" },
  privacy: {
    metaTitle: "Privatlivspolitik | IoT Fabrikken",
    lastUpdatedDate: "22. maj 2026",
    ctaTitle: "Spørgsmål om dine data?",
    ctaSubtitle:
      "Kontakt os, vi svarer på hverdage og kan henvise dig til den rette person for GDPR- eller produktspecifikke henvendelser.",
    body: `
    <p>Denne privatlivspolitik beskriver, hvordan IoT Fabrikken ApS ("<strong>IoT Fabrikken</strong>", "<strong>vi</strong>", "<strong>os</strong>" eller "<strong>vores</strong>") indsamler, bruger og deler personoplysninger, når du bruger vores website, RoomAlyzer-platformen og relaterede tjenester (samlet "<strong>Tjenesten</strong>"). Den forklarer også dine privatlivsrettigheder, og hvordan gældende lovgivning beskytter dig.</p>
    <p>Vi bruger personoplysninger til at levere og forbedre Tjenesten. Ved at bruge Tjenesten accepterer du indsamling og brug af oplysninger i overensstemmelse med denne privatlivspolitik. Når vi behandler personoplysninger på vegne af en kunde (for eksempel sensoraflæsninger og bygningsdata i RoomAlyzer), handler vi som <strong>databehandler</strong> efter kundens instruks; kundens privatlivsmeddelelse og databehandleraftale gælder for den behandling.</p>
    <h2>Fortolkning og definitioner</h2>
    <h3>Fortolkning</h3>
    <p>Ord med stort begyndelsesbogstav har de betydninger, der er angivet nedenfor. Samme betydning gælder, uanset om de optræder i ental eller flertal.</p>
    <h3>Definitioner</h3>
    <p>I denne privatlivspolitik gælder følgende:</p>
    <ul>
      <li><strong>Konto</strong> betyder en unik konto, der er oprettet til dig for at få adgang til dele af Tjenesten.</li>
      <li><strong>Tilknyttet selskab</strong> betyder en enhed, der kontrollerer, kontrolleres af eller er under fælles kontrol med en part, hvor "kontrol" betyder ejerskab af 50% eller mere af aktierne, kapitalandelene eller andre værdipapirer med stemmeret til valg af bestyrelse eller anden ledelse.</li>
      <li><strong>Applikation</strong> betyder den RoomAlyzer-software, som Virksomheden stiller til rådighed, herunder webapplikationen på app.roomalyzer.com og relaterede mobil- eller integrationsgrænseflader.</li>
      <li><strong>Virksomheden</strong> (omtalt som "Virksomheden", "Vi", "Os" eller "Vores") betyder IoT Fabrikken ApS, Brønsager 1, 4000 Roskilde, Danmark (CVR 39 11 03 93).</li>
      <li><strong>Land</strong> betyder Danmark.</li>
      <li><strong>Enhed</strong> betyder enhver enhed, der kan tilgå Tjenesten, såsom en computer, mobiltelefon eller tablet.</li>
      <li><strong>Personoplysninger</strong> betyder enhver information, der vedrører en identificeret eller identificerbar fysisk person.</li>
      <li><strong>Tjeneste</strong> betyder webstedet iot-fabrikken.com (og relaterede domæner), Applikationen, kundesupportportaler, demo- og kontaktflows, nyhedsbreve og enhver anden tjeneste, vi driver, og som linker til denne politik.</li>
      <li><strong>Tjenesteudbyder</strong> betyder en fysisk eller juridisk person, der behandler data på vegne af Virksomheden for at facilitere Tjenesten, levere Tjenesten på vores vegne, udføre tjenester relateret til Tjenesten eller hjælpe os med at analysere, hvordan Tjenesten bruges.</li>
      <li><strong>Brugsdata</strong> betyder data, der indsamles automatisk, enten genereret ved brug af Tjenesten eller fra selve Tjenestens infrastruktur (for eksempel varigheden af et sidebesøg eller metadata for en API-forespørgsel).</li>
      <li><strong>Du</strong> betyder den person, der tilgår eller bruger Tjenesten, eller den virksomhed eller anden juridisk enhed, på hvis vegne en sådan person tilgår eller bruger Tjenesten, alt efter hvad der er relevant.</li>
    </ul>
    <h2>Indsamling og brug af dine personoplysninger</h2>
    <h3>Personoplysninger</h3>
    <p>Når du bruger vores Tjeneste, kan vi bede dig om at give personoplysninger, der kan bruges til at kontakte eller identificere dig. Dette kan omfatte, men er ikke begrænset til:</p>
    <ul>
      <li>E-mailadresse</li>
      <li>Fornavn og efternavn</li>
      <li>Telefonnummer</li>
      <li>Virksomheds- eller organisationsnavn og jobtitel</li>
      <li>Adresse, by, region og postnummer (hvor det er relevant for ordrer eller kontrakter)</li>
      <li>Loginoplysninger og profilpræferencer</li>
      <li>Indholdet af de beskeder, du sender os (support, salg, demoforespørgsler)</li>
      <li>Brugsdata</li>
    </ul>
    <h3>Brugsdata</h3>
    <p>Brugsdata indsamles automatisk, når du bruger Tjenesten.</p>
    <p>Brugsdata kan omfatte din Enheds internetprotokoladresse (IP-adresse), browsertype og -version, de sider du besøger, tidspunktet og datoen for dit besøg, den tid du bruger på disse sider, unikke enheds-id'er og andre diagnostiske data.</p>
    <p>Når du tilgår Tjenesten via en mobil enhed, kan vi indsamle oplysninger såsom typen af mobil enhed, unikt enheds-id, IP-adresse, mobilt styresystem, mobilbrowsertype og andre diagnostiske data.</p>
    <p>Vi kan også indsamle oplysninger, som din browser sender, når du besøger vores website, eller når du tilgår Tjenesten via en mobil enhed. For cookies og lignende teknologier henvises til vores <a href="/da/legal/cookies/">Cookiepolitik</a>.</p>
    <h3>Sådan bruger vi dine personoplysninger</h3>
    <p>Virksomheden kan bruge Personoplysninger til følgende formål:</p>
    <ul>
      <li><strong>At levere og vedligeholde vores Tjeneste</strong>, herunder at overvåge brugen og drive Applikationen.</li>
      <li><strong>At administrere din Konto</strong> og give dig adgang til funktionalitet, der er tilgængelig for registrerede brugere.</li>
      <li><strong>At opfylde en kontrakt</strong> vedrørende produkter eller tjenester, du har købt, eller enhver anden kontrakt med os via Tjenesten.</li>
      <li><strong>At kontakte dig</strong> via e-mail, telefon, SMS eller anden elektronisk kommunikation om opdateringer, sikkerhedsmeddelelser, support eller information om funktioner, produkter eller aftalte tjenester, hvor det er nødvendigt eller rimeligt.</li>
      <li><strong>At give nyheder og tilbud</strong> om varer, tjenester og begivenheder, der ligner dem, du har købt eller forespurgt om, medmindre du har frabedt dig dette.</li>
      <li><strong>At håndtere dine henvendelser</strong> til os (salg, support, demoer, karriere).</li>
      <li><strong>Ved virksomhedsoverdragelser</strong> såsom en fusion, frasalg, omstrukturering, reorganisering, opløsning eller salg af aktiver, hvor Personoplysninger om Tjenestens brugere kan være blandt de overdragne aktiver.</li>
      <li><strong>Til andre formål</strong> såsom dataanalyse, identifikation af brugsmønstre, måling af kampagners effektivitet og forbedring af vores Tjeneste, produkter, tjenester, markedsføring og din oplevelse.</li>
    </ul>
    <h3>Retsgrundlag (EØS og UK)</h3>
    <p>Hvor databeskyttelsesforordningen (GDPR) eller UK GDPR finder anvendelse, baserer vi os på et eller flere af følgende retsgrundlag: opfyldelse af en kontrakt, legitime interesser (for eksempel drift og sikring af Tjenesten, B2B-markedsføring til eksisterende kunder), overholdelse af en retlig forpligtelse og samtykke, hvor det kræves (for eksempel visse cookies eller markedsføringstilmeldinger). Du kan til enhver tid trække dit samtykke tilbage, uden at det påvirker lovligheden af behandlingen før tilbagetrækningen.</p>
    <h3>Deling af dine personoplysninger</h3>
    <p>Vi kan dele dine personoplysninger i følgende situationer:</p>
    <ul>
      <li><strong>Med Tjenesteudbydere</strong>, der hjælper os med at drive Tjenesten, hosting, analyser, e-maillevering, CRM, betalingsbehandling eller kundesupport, underlagt passende kontraktuelle sikkerhedsforanstaltninger.</li>
      <li><strong>Ved virksomhedsoverdragelser</strong> i forbindelse med eller under forhandlinger om en fusion, salg af Virksomhedens aktiver, finansiering eller opkøb.</li>
      <li><strong>Med Tilknyttede selskaber</strong>, som vi forpligter til at overholde denne privatlivspolitik.</li>
      <li><strong>Med forretningspartnere</strong> for at tilbyde visse produkter, tjenester eller kampagner, hvor du har valgt at deltage.</li>
      <li><strong>Med andre brugere</strong>, når du deler personoplysninger eller interagerer i offentlige områder af Tjenesten, hvor sådanne oplysninger kan være synlige for andre.</li>
      <li><strong>Med dit samtykke</strong> til ethvert andet formål, du har accepteret.</li>
      <li><strong>Med myndigheder</strong>, hvor det kræves ved lov, eller for at beskytte rettigheder, sikkerhed og tryghed som beskrevet nedenfor.</li>
    </ul>
    <p>En aktuel liste over underdatabehandlere, der bruges til RoomAlyzer-kundedata, er tilgængelig for kunder under vores <a href="/da/legal/terms/">Vilkår og databehandleraftale</a>.</p>
    <h2>Opbevaring af dine personoplysninger</h2>
    <p>Vi opbevarer kun Personoplysninger, så længe det er nødvendigt til de formål, der er angivet i denne privatlivspolitik, herunder for at overholde retlige forpligtelser, løse tvister og håndhæve aftaler.</p>
    <p>Brugsdata opbevares generelt i en kortere periode, undtagen når de bruges til at styrke sikkerheden eller forbedre funktionaliteten, eller hvor vi er lovmæssigt forpligtet til at opbevare dem længere.</p>
    <h2>Overførsel af dine personoplysninger</h2>
    <p>Dine oplysninger, herunder Personoplysninger, behandles på Virksomhedens kontorer og andre steder, hvor de parter, der er involveret i behandlingen, befinder sig. Data kan overføres til (og opbevares på) systemer uden for dit land, hvor databeskyttelseslovgivningen kan være anderledes.</p>
    <p>For kundedata i RoomAlyzer tilbyder vi som standard <strong>EU-dataopbevaring</strong>. Hvor der sker overførsler uden for Det Europæiske Økonomiske Samarbejdsområde, bruger vi passende sikkerhedsforanstaltninger såsom standardkontraktbestemmelser eller tilsvarende mekanismer, medmindre en tilstrækkelighedsafgørelse finder anvendelse.</p>
    <p>Dit samtykke til denne privatlivspolitik efterfulgt af din indsendelse af oplysninger udgør din accept af en sådan overførsel, hvor det er relevant. Vi træffer de foranstaltninger, der med rimelighed er nødvendige for at sikre, at dine data behandles sikkert og i overensstemmelse med denne privatlivspolitik.</p>
    <h2>Videregivelse af dine personoplysninger</h2>
    <h3>Forretningstransaktioner</h3>
    <p>Hvis Virksomheden er involveret i en fusion, et opkøb eller et salg af aktiver, kan dine Personoplysninger blive overført. Vi giver besked, før dine Personoplysninger overføres og bliver underlagt en anden privatlivspolitik.</p>
    <h3>Retshåndhævelse og andre retlige krav</h3>
    <p>Under visse omstændigheder kan Virksomheden være forpligtet til at videregive dine Personoplysninger, hvis det kræves ved lov eller som svar på gyldige anmodninger fra offentlige myndigheder (for eksempel en domstol eller en offentlig myndighed). Vi kan videregive Personoplysninger, hvor vi i god tro mener, at videregivelse er nødvendig for at:</p>
    <ul>
      <li>Overholde en retlig forpligtelse</li>
      <li>Beskytte og forsvare Virksomhedens rettigheder eller ejendom</li>
      <li>Forhindre eller undersøge mulige forseelser i forbindelse med Tjenesten</li>
      <li>Beskytte den personlige sikkerhed for Tjenestens brugere eller offentligheden</li>
      <li>Beskytte mod retligt ansvar</li>
    </ul>
    <h2>Sikkerhed for dine personoplysninger</h2>
    <p>Sikkerheden af dine Personoplysninger er vigtig for os. Vi bruger kommercielt acceptable tekniske og organisatoriske foranstaltninger, herunder kryptering under overførsel og i hvile for Applikationen, adgangskontroller og regelmæssig sikkerhedstest. Ingen metode til transmission over internettet eller elektronisk lagring er 100% sikker; vi kan ikke garantere absolut sikkerhed. Yderligere detaljer findes på vores <a href="/da/legal/security/">Sikkerhed</a>-side og i kundedokumentationen.</p>
    <h2>Dine privatlivsrettigheder</h2>
    <p>Afhængigt af hvor du bor, kan du have ret til indsigt, berigtigelse, sletning, begrænsning af eller indsigelse mod behandling, dataportabilitet og til at indgive en klage til en tilsynsmyndighed. Hvis du er slutbruger af en kundes RoomAlyzer-implementering, bedes du først kontakte den pågældende kunde; vi bistår vores kunder med at besvare anmodninger fra registrerede som databehandler.</p>
    <p>For at udøve rettigheder vedrørende data, som vi kontrollerer direkte (for eksempel webkonti, markedsførings- eller salgsforespørgsler), kan du kontakte os via oplysningerne nedenfor. Vi kan have brug for at verificere din identitet, før vi svarer.</p>
    <h2>Børns privatliv</h2>
    <p>Vores Tjeneste henvender sig ikke til personer under 13 år. Vi indsamler ikke bevidst personligt identificerbare oplysninger fra personer under 13 år. Hvis du er forælder eller værge og mener, at dit barn har givet os Personoplysninger, bedes du kontakte os. Hvis vi bliver opmærksomme på, at vi har indsamlet Personoplysninger fra en person under 13 år uden verifikation af forældresamtykke, træffer vi foranstaltninger for at fjerne disse oplysninger fra vores servere.</p>
    <p>Hvor vi baserer os på samtykke som retsgrundlag, og dit land kræver samtykke fra en forælder, kan vi kræve forældresamtykke, før vi indsamler og bruger disse oplysninger.</p>
    <h2>Links til andre websites</h2>
    <p>Vores Tjeneste kan indeholde links til websites, der ikke drives af os. Hvis du klikker på et tredjepartslink, bliver du ledt til den pågældende tredjeparts site. Vi anbefaler kraftigt, at du gennemgår privatlivspolitikken for hvert site, du besøger. Vi har ingen kontrol over og påtager os intet ansvar for indholdet, privatlivspolitikkerne eller praksis på tredjeparts sites eller tjenester.</p>
    <h2>Ændringer af denne privatlivspolitik</h2>
    <p>Vi kan opdatere denne privatlivspolitik fra tid til anden. Vi giver dig besked om væsentlige ændringer ved at offentliggøre den nye privatlivspolitik på denne side og opdatere datoen for "Senest opdateret". Hvor det er relevant, kan vi også give dig besked via e-mail eller gennem en tydelig meddelelse i Tjenesten, før ændringerne træder i kraft.</p>
    <p>Vi anbefaler, at du gennemgår denne privatlivspolitik med jævne mellemrum. Ændringer træder i kraft, når de offentliggøres på denne side.</p>
    <h2>Kontakt os</h2>
    <p>Hvis du har spørgsmål til denne privatlivspolitik eller vores brug af dine personoplysninger, kan du kontakte os:</p>
    <ul>
      <li><strong>E-mail:</strong> <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a> (generelle henvendelser og privatliv)</li>
      <li><strong>Produktsupport:</strong> <a href="mailto:support@iot-fabrikken.com">support@iot-fabrikken.com</a></li>
      <li><strong>Telefon:</strong> <a href="tel:+4571718090">+45 71 71 80 90</a></li>
      <li><strong>Post:</strong> IoT Fabrikken ApS, Brønsager 1, 4000 Roskilde, Danmark</li>
    </ul>
    `,
  },
  cookies: {
    metaTitle: "Cookiepolitik | IoT Fabrikken",
    lastUpdatedDate: "7. juli 2026",
    ctaTitle: "Spørgsmål om cookies eller måling?",
    ctaSubtitle:
      "Kontakt os, hvis du har brug for hjælp til at ændre dine præferencer eller ønsker flere oplysninger om, hvordan vi måler kampagner.",
    body: `
    <p>Denne cookiepolitik beskriver, hvordan IoT Fabrikken ApS ("<strong>vi</strong>") bruger cookies og lignende teknologier på iot-fabrikken.com ("<strong>websitet</strong>"). Den bør læses sammen med vores <a href="/da/legal/privacy/">Privatlivspolitik</a>.</p>
    <h2>Hvad er cookies?</h2>
    <p>Cookies er små tekstfiler, der gemmes på din enhed, når du besøger et website. Lignende teknologier omfatter local storage (til dit cookievalg) og session storage (til kortvarig attributtering under et besøg).</p>
    <h2>Sådan bruger vi cookies</h2>
    <p>Vi opdeler cookies i tre kategorier. Du kan acceptere eller afvise valgfrie kategorier via cookiebanneret eller "Cookieindstillinger".</p>
    <h3>Nødvendige</h3>
    <p>Påkrævet for at huske dit cookievalg. De sporer dig ikke på tværs af sites.</p>
    <ul><li><strong>Samtykkepræference</strong> — gemmer dit valg (local storage, op til 12 måneder).</li></ul>
    <h3>Analyse (valgfri)</h3>
    <p>Hjælper os med at forstå, hvordan besøgende bruger websitet. Indlæses kun med samtykke via Google Tag Manager, Google Analytics 4 (GA4) og Microsoft Clarity (heatmaps og sessionoptagelser).</p>
    <ul>
      <li><strong>_ga, _ga_*</strong> — skelner mellem brugere og sessioner (op til 24 måneder).</li>
      <li><strong>_gid</strong> — skelner mellem brugere (24 timer).</li>
      <li><strong>_clck, _clsk, CLID, ANONCHK, MR, MUID, SM</strong> — Clarity-session og heatmap-id'er (Microsoft, typisk op til 1 år; sessionoptagelse er sampled).</li>
    </ul>
    <h3>Marketing (valgfri)</h3>
    <p>Måler Google Ads-kampagner og understøtter remarketing, hvor det er tilladt. Indlæses kun med samtykke.</p>
    <ul><li><strong>_gcl_*</strong> — Google Ads-konverterings- og klik-id'er (typisk 90 dage).</li></ul>
    <h2>Retsgrundlag</h2>
    <p>Nødvendig lagring bygger på vores legitime interesse i at drive websitet. Analyse- og marketingcookies sættes kun efter samtykke. Du kan til enhver tid trække samtykket tilbage via "Cookieindstillinger".</p>
    <h2>Administration</h2>
    <p>Brug cookiebanneret ved første besøg, eller klik <strong>Cookieindstillinger</strong> (nederst til venstre) for at ændre valget senere. Du kan også blokere cookies i browseren.</p>
    <h2>Kontakt</h2>
    <p>Spørgsmål om cookies: <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a>.</p>
    `,
  },
};

const de: LegalStrings = {
  common: { home: "Startseite", legal: "Rechtliches", lastUpdated: "Zuletzt aktualisiert:" },
  privacy: {
    metaTitle: "Datenschutzerklärung | IoT Fabrikken",
    lastUpdatedDate: "22. Mai 2026",
    ctaTitle: "Fragen zu Ihren Daten?",
    ctaSubtitle:
      "Kontaktieren Sie uns, wir antworten an Werktagen und verweisen Sie an die richtige Person für DSGVO- oder produktspezifische Anfragen.",
    body: `
    <p>Diese Datenschutzerklärung beschreibt, wie die IoT Fabrikken ApS ("<strong>IoT Fabrikken</strong>", "<strong>wir</strong>", "<strong>uns</strong>" oder "<strong>unser</strong>") personenbezogene Daten erhebt, verwendet und weitergibt, wenn Sie unsere Website, die RoomAlyzer-Plattform und zugehörige Dienste (zusammen der "<strong>Dienst</strong>") nutzen. Sie erläutert außerdem Ihre Datenschutzrechte und wie das geltende Recht Sie schützt.</p>
    <p>Wir verwenden personenbezogene Daten, um den Dienst bereitzustellen und zu verbessern. Durch die Nutzung des Dienstes stimmen Sie der Erhebung und Verwendung von Informationen gemäß dieser Datenschutzerklärung zu. Soweit wir personenbezogene Daten im Auftrag eines Kunden verarbeiten (zum Beispiel Sensormesswerte und Gebäudedaten in RoomAlyzer), handeln wir als <strong>Auftragsverarbeiter</strong> nach Weisung des Kunden; für diese Verarbeitung gelten die Datenschutzhinweise und der Auftragsverarbeitungsvertrag des Kunden.</p>
    <h2>Auslegung und Begriffsbestimmungen</h2>
    <h3>Auslegung</h3>
    <p>Begriffe mit großem Anfangsbuchstaben haben die nachstehend festgelegte Bedeutung. Dieselbe Bedeutung gilt unabhängig davon, ob sie im Singular oder Plural verwendet werden.</p>
    <h3>Begriffsbestimmungen</h3>
    <p>Für die Zwecke dieser Datenschutzerklärung gilt:</p>
    <ul>
      <li><strong>Konto</strong> bezeichnet ein eindeutiges Konto, das für Sie erstellt wird, um auf Teile des Dienstes zuzugreifen.</li>
      <li><strong>Verbundenes Unternehmen</strong> bezeichnet eine Einheit, die eine Partei kontrolliert, von ihr kontrolliert wird oder mit ihr unter gemeinsamer Kontrolle steht, wobei "Kontrolle" den Besitz von 50% oder mehr der Anteile, Kapitalbeteiligungen oder sonstigen stimmberechtigten Wertpapiere zur Wahl von Geschäftsführern oder anderen Leitungsorganen bedeutet.</li>
      <li><strong>Anwendung</strong> bezeichnet die von dem Unternehmen bereitgestellte RoomAlyzer-Software, einschließlich der Webanwendung unter app.roomalyzer.com und zugehöriger Mobil- oder Integrationsschnittstellen.</li>
      <li><strong>Das Unternehmen</strong> (bezeichnet als "das Unternehmen", "Wir", "Uns" oder "Unser") bezeichnet die IoT Fabrikken ApS, Brønsager 1, 4000 Roskilde, Dänemark (CVR 39 11 03 93).</li>
      <li><strong>Land</strong> bezeichnet Dänemark.</li>
      <li><strong>Gerät</strong> bezeichnet jedes Gerät, das auf den Dienst zugreifen kann, etwa einen Computer, ein Mobiltelefon oder ein Tablet.</li>
      <li><strong>Personenbezogene Daten</strong> bezeichnet alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person beziehen.</li>
      <li><strong>Dienst</strong> bezeichnet die Website iot-fabrikken.com (und zugehörige Domains), die Anwendung, Kundensupport-Portale, Demo- und Kontaktabläufe, Newsletter und alle anderen von uns betriebenen Dienste, die auf diese Erklärung verweisen.</li>
      <li><strong>Dienstanbieter</strong> bezeichnet eine natürliche oder juristische Person, die Daten im Auftrag des Unternehmens verarbeitet, um den Dienst zu erleichtern, den Dienst in unserem Auftrag bereitzustellen, mit dem Dienst zusammenhängende Leistungen zu erbringen oder uns bei der Analyse der Nutzung des Dienstes zu unterstützen.</li>
      <li><strong>Nutzungsdaten</strong> bezeichnet Daten, die automatisch erhoben werden, sei es durch die Nutzung des Dienstes oder aus der Infrastruktur des Dienstes selbst (zum Beispiel die Dauer eines Seitenbesuchs oder Metadaten einer API-Anfrage).</li>
      <li><strong>Sie</strong> bezeichnet die Person, die auf den Dienst zugreift oder ihn nutzt, oder das Unternehmen bzw. die andere juristische Person, in deren Namen diese Person auf den Dienst zugreift oder ihn nutzt, je nach Sachlage.</li>
    </ul>
    <h2>Erhebung und Verwendung Ihrer personenbezogenen Daten</h2>
    <h3>Personenbezogene Daten</h3>
    <p>Während Sie unseren Dienst nutzen, bitten wir Sie möglicherweise, personenbezogene Daten anzugeben, die zur Kontaktaufnahme oder Identifizierung verwendet werden können. Dies kann unter anderem umfassen:</p>
    <ul>
      <li>E-Mail-Adresse</li>
      <li>Vor- und Nachname</li>
      <li>Telefonnummer</li>
      <li>Firmen- oder Organisationsname und Berufsbezeichnung</li>
      <li>Anschrift, Stadt, Region und Postleitzahl (sofern für Bestellungen oder Verträge relevant)</li>
      <li>Zugangsdaten und Profileinstellungen</li>
      <li>Inhalt der Nachrichten, die Sie uns senden (Support, Vertrieb, Demo-Anfragen)</li>
      <li>Nutzungsdaten</li>
    </ul>
    <h3>Nutzungsdaten</h3>
    <p>Nutzungsdaten werden automatisch erhoben, wenn Sie den Dienst nutzen.</p>
    <p>Nutzungsdaten können die Internetprotokolladresse (IP-Adresse) Ihres Geräts, Browsertyp und -version, die von Ihnen besuchten Seiten, Uhrzeit und Datum Ihres Besuchs, die auf diesen Seiten verbrachte Zeit, eindeutige Gerätekennungen und andere Diagnosedaten umfassen.</p>
    <p>Wenn Sie über ein Mobilgerät auf den Dienst zugreifen, können wir Informationen wie den Typ des Mobilgeräts, die eindeutige Geräte-ID, die IP-Adresse, das mobile Betriebssystem, den Typ des mobilen Browsers und andere Diagnosedaten erheben.</p>
    <p>Wir können auch Informationen erheben, die Ihr Browser sendet, wenn Sie unsere Website besuchen oder über ein Mobilgerät auf den Dienst zugreifen. Zu Cookies und ähnlichen Technologien siehe unsere <a href="/de/legal/cookies/">Cookie-Richtlinie</a>.</p>
    <h3>Wie wir Ihre personenbezogenen Daten verwenden</h3>
    <p>Das Unternehmen kann personenbezogene Daten für folgende Zwecke verwenden:</p>
    <ul>
      <li><strong>Zur Bereitstellung und Aufrechterhaltung unseres Dienstes</strong>, einschließlich der Überwachung der Nutzung und des Betriebs der Anwendung.</li>
      <li><strong>Zur Verwaltung Ihres Kontos</strong> und um Ihnen Zugang zu Funktionen für registrierte Nutzer zu gewähren.</li>
      <li><strong>Zur Erfüllung eines Vertrags</strong> über Produkte oder Dienstleistungen, die Sie erworben haben, oder eines anderen Vertrags mit uns über den Dienst.</li>
      <li><strong>Um Sie zu kontaktieren</strong> per E-Mail, Telefon, SMS oder anderer elektronischer Kommunikation in Bezug auf Aktualisierungen, Sicherheitshinweise, Support oder Informationen zu Funktionen, Produkten oder vertraglich vereinbarten Leistungen, soweit erforderlich oder angemessen.</li>
      <li><strong>Um Neuigkeiten und Angebote</strong> zu Waren, Dienstleistungen und Veranstaltungen bereitzustellen, die denen ähneln, die Sie erworben oder zu denen Sie angefragt haben, sofern Sie dem nicht widersprochen haben.</li>
      <li><strong>Zur Bearbeitung Ihrer Anfragen</strong> an uns (Vertrieb, Support, Demos, Karriere).</li>
      <li><strong>Bei Unternehmensübertragungen</strong> wie einer Fusion, Veräußerung, Umstrukturierung, Reorganisation, Auflösung oder einem Verkauf von Vermögenswerten, bei denen personenbezogene Daten über Nutzer des Dienstes zu den übertragenen Vermögenswerten gehören können.</li>
      <li><strong>Für andere Zwecke</strong> wie Datenanalyse, Ermittlung von Nutzungstrends, Messung der Wirksamkeit von Werbeaktionen sowie Verbesserung unseres Dienstes, unserer Produkte, Dienstleistungen, unseres Marketings und Ihrer Erfahrung.</li>
    </ul>
    <h3>Rechtsgrundlagen (EWR und UK)</h3>
    <p>Soweit die Datenschutz-Grundverordnung (DSGVO) oder die UK-DSGVO Anwendung findet, stützen wir uns auf eine oder mehrere der folgenden Rechtsgrundlagen: Erfüllung eines Vertrags, berechtigte Interessen (zum Beispiel Betrieb und Absicherung des Dienstes, B2B-Marketing gegenüber bestehenden Kunden), Erfüllung einer rechtlichen Verpflichtung sowie Einwilligung, soweit erforderlich (zum Beispiel bestimmte Cookies oder Marketing-Anmeldungen). Sie können Ihre Einwilligung jederzeit widerrufen, ohne dass die Rechtmäßigkeit der vor dem Widerruf erfolgten Verarbeitung berührt wird.</p>
    <h3>Weitergabe Ihrer personenbezogenen Daten</h3>
    <p>Wir können Ihre personenbezogenen Daten in folgenden Situationen weitergeben:</p>
    <ul>
      <li><strong>An Dienstanbieter</strong>, die uns beim Betrieb des Dienstes, beim Hosting, bei Analysen, beim E-Mail-Versand, CRM, bei der Zahlungsabwicklung oder im Kundensupport unterstützen, vorbehaltlich angemessener vertraglicher Schutzmaßnahmen.</li>
      <li><strong>Bei Unternehmensübertragungen</strong> im Zusammenhang mit oder während der Verhandlungen über eine Fusion, einen Verkauf von Unternehmensvermögen, eine Finanzierung oder eine Übernahme.</li>
      <li><strong>An verbundene Unternehmen</strong>, die wir zur Einhaltung dieser Datenschutzerklärung verpflichten.</li>
      <li><strong>An Geschäftspartner</strong>, um bestimmte Produkte, Dienstleistungen oder Aktionen anzubieten, an denen Sie teilnehmen möchten.</li>
      <li><strong>An andere Nutzer</strong>, wenn Sie personenbezogene Daten teilen oder in öffentlichen Bereichen des Dienstes interagieren, wo solche Informationen für andere sichtbar sein können.</li>
      <li><strong>Mit Ihrer Einwilligung</strong> für jeden anderen Zweck, dem Sie zugestimmt haben.</li>
      <li><strong>An Behörden</strong>, soweit gesetzlich vorgeschrieben oder zum Schutz von Rechten, Sicherheit und Schutz wie nachstehend beschrieben.</li>
    </ul>
    <p>Eine aktuelle Liste der für RoomAlyzer-Kundendaten eingesetzten Auftragsverarbeiter steht Kunden im Rahmen unserer <a href="/de/legal/terms/">Bedingungen und des Auftragsverarbeitungsvertrags</a> zur Verfügung.</p>
    <h2>Speicherung Ihrer personenbezogenen Daten</h2>
    <p>Wir speichern personenbezogene Daten nur so lange, wie es für die in dieser Datenschutzerklärung genannten Zwecke erforderlich ist, einschließlich der Erfüllung rechtlicher Verpflichtungen, der Beilegung von Streitigkeiten und der Durchsetzung von Vereinbarungen.</p>
    <p>Nutzungsdaten werden in der Regel für einen kürzeren Zeitraum gespeichert, außer wenn sie zur Stärkung der Sicherheit oder zur Verbesserung der Funktionalität verwendet werden oder wir gesetzlich verpflichtet sind, sie länger zu speichern.</p>
    <h2>Übermittlung Ihrer personenbezogenen Daten</h2>
    <p>Ihre Informationen, einschließlich personenbezogener Daten, werden in den Büros des Unternehmens und an anderen Orten verarbeitet, an denen sich die an der Verarbeitung beteiligten Parteien befinden. Daten können an Systeme außerhalb Ihres Landes übermittelt und dort gespeichert werden, wo die Datenschutzgesetze abweichen können.</p>
    <p>Für Kundendaten in RoomAlyzer bieten wir standardmäßig <strong>EU-Datenhaltung</strong> an. Soweit Übermittlungen außerhalb des Europäischen Wirtschaftsraums erfolgen, verwenden wir geeignete Schutzmaßnahmen wie Standardvertragsklauseln oder gleichwertige Mechanismen, sofern kein Angemessenheitsbeschluss gilt.</p>
    <p>Ihre Einwilligung in diese Datenschutzerklärung gefolgt von der Übermittlung Ihrer Informationen stellt gegebenenfalls Ihr Einverständnis mit einer solchen Übermittlung dar. Wir treffen die nach billigem Ermessen erforderlichen Maßnahmen, um sicherzustellen, dass Ihre Daten sicher und im Einklang mit dieser Datenschutzerklärung behandelt werden.</p>
    <h2>Offenlegung Ihrer personenbezogenen Daten</h2>
    <h3>Geschäftliche Transaktionen</h3>
    <p>Ist das Unternehmen an einer Fusion, Übernahme oder einem Verkauf von Vermögenswerten beteiligt, können Ihre personenbezogenen Daten übertragen werden. Wir werden Sie benachrichtigen, bevor Ihre personenbezogenen Daten übertragen werden und einer anderen Datenschutzerklärung unterliegen.</p>
    <h3>Strafverfolgung und sonstige rechtliche Anforderungen</h3>
    <p>Unter bestimmten Umständen kann das Unternehmen verpflichtet sein, Ihre personenbezogenen Daten offenzulegen, sofern dies gesetzlich vorgeschrieben ist oder auf rechtmäßige Anfragen von Behörden (zum Beispiel eines Gerichts oder einer Behörde) hin erfolgt. Wir können personenbezogene Daten offenlegen, wenn wir in gutem Glauben der Ansicht sind, dass eine Offenlegung erforderlich ist, um:</p>
    <ul>
      <li>einer rechtlichen Verpflichtung nachzukommen</li>
      <li>die Rechte oder das Eigentum des Unternehmens zu schützen und zu verteidigen</li>
      <li>mögliches Fehlverhalten im Zusammenhang mit dem Dienst zu verhindern oder zu untersuchen</li>
      <li>die persönliche Sicherheit der Nutzer des Dienstes oder der Öffentlichkeit zu schützen</li>
      <li>vor rechtlicher Haftung zu schützen</li>
    </ul>
    <h2>Sicherheit Ihrer personenbezogenen Daten</h2>
    <p>Die Sicherheit Ihrer personenbezogenen Daten ist uns wichtig. Wir setzen wirtschaftlich vertretbare technische und organisatorische Maßnahmen ein, einschließlich Verschlüsselung bei der Übertragung und im Ruhezustand für die Anwendung, Zugriffskontrollen und regelmäßige Sicherheitstests. Keine Methode der Übertragung über das Internet oder der elektronischen Speicherung ist zu 100% sicher; wir können keine absolute Sicherheit garantieren. Weitere Einzelheiten finden Sie auf unserer Seite <a href="/de/legal/security/">Sicherheit</a> und in der Kundendokumentation.</p>
    <h2>Ihre Datenschutzrechte</h2>
    <p>Je nachdem, wo Sie leben, haben Sie möglicherweise das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der oder Widerspruch gegen die Verarbeitung, Datenübertragbarkeit sowie das Recht, eine Beschwerde bei einer Aufsichtsbehörde einzureichen. Wenn Sie Endnutzer der RoomAlyzer-Bereitstellung eines Kunden sind, wenden Sie sich bitte zuerst an diesen Kunden; wir unterstützen unsere Kunden als Auftragsverarbeiter bei der Beantwortung von Betroffenenanfragen.</p>
    <p>Um Rechte in Bezug auf Daten auszuüben, die wir direkt kontrollieren (zum Beispiel Website-Konten, Marketing- oder Vertriebsanfragen), kontaktieren Sie uns über die nachstehenden Angaben. Möglicherweise müssen wir Ihre Identität überprüfen, bevor wir antworten.</p>
    <h2>Datenschutz von Kindern</h2>
    <p>Unser Dienst richtet sich nicht an Personen unter 13 Jahren. Wir erheben nicht wissentlich personenbezogene Daten von Personen unter 13 Jahren. Wenn Sie ein Elternteil oder Erziehungsberechtigter sind und der Ansicht sind, dass Ihr Kind uns personenbezogene Daten übermittelt hat, kontaktieren Sie uns bitte. Wenn wir feststellen, dass wir personenbezogene Daten von Personen unter 13 Jahren ohne Überprüfung der Einwilligung der Eltern erhoben haben, ergreifen wir Maßnahmen, um diese Informationen von unseren Servern zu entfernen.</p>
    <p>Soweit wir uns auf eine Einwilligung als Rechtsgrundlage stützen und Ihr Land die Einwilligung eines Elternteils verlangt, können wir die Einwilligung der Eltern verlangen, bevor wir diese Informationen erheben und verwenden.</p>
    <h2>Links zu anderen Websites</h2>
    <p>Unser Dienst kann Links zu Websites enthalten, die nicht von uns betrieben werden. Wenn Sie auf einen Link eines Dritten klicken, werden Sie auf die Website dieses Dritten weitergeleitet. Wir empfehlen Ihnen dringend, die Datenschutzerklärung jeder von Ihnen besuchten Website zu prüfen. Wir haben keine Kontrolle über und übernehmen keine Verantwortung für die Inhalte, Datenschutzerklärungen oder Praktiken von Websites oder Diensten Dritter.</p>
    <h2>Änderungen dieser Datenschutzerklärung</h2>
    <p>Wir können diese Datenschutzerklärung von Zeit zu Zeit aktualisieren. Wir werden Sie über wesentliche Änderungen informieren, indem wir die neue Datenschutzerklärung auf dieser Seite veröffentlichen und das Datum "Zuletzt aktualisiert" anpassen. Sofern angemessen, können wir Sie auch per E-Mail oder durch einen deutlichen Hinweis im Dienst informieren, bevor die Änderungen wirksam werden.</p>
    <p>Es wird empfohlen, diese Datenschutzerklärung regelmäßig zu überprüfen. Änderungen werden wirksam, sobald sie auf dieser Seite veröffentlicht werden.</p>
    <h2>Kontakt</h2>
    <p>Wenn Sie Fragen zu dieser Datenschutzerklärung oder zur Verwendung Ihrer personenbezogenen Daten haben, kontaktieren Sie uns:</p>
    <ul>
      <li><strong>E-Mail:</strong> <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a> (allgemeine Anfragen und Datenschutz)</li>
      <li><strong>Produktsupport:</strong> <a href="mailto:support@iot-fabrikken.com">support@iot-fabrikken.com</a></li>
      <li><strong>Telefon:</strong> <a href="tel:+4571718090">+45 71 71 80 90</a></li>
      <li><strong>Post:</strong> IoT Fabrikken ApS, Brønsager 1, 4000 Roskilde, Dänemark</li>
    </ul>
    `,
  },
  cookies: {
    metaTitle: "Cookie-Richtlinie | IoT Fabrikken",
    lastUpdatedDate: "7. Juli 2026",
    ctaTitle: "Fragen zu Cookies oder Messung?",
    ctaSubtitle:
      "Kontaktieren Sie uns, wenn Sie Hilfe bei Ihren Einstellungen benötigen oder mehr über unsere Kampagnenmessung erfahren möchten.",
    body: `
    <p>Diese Cookie-Richtlinie erläutert, wie IoT Fabrikken ApS ("<strong>wir</strong>") Cookies und ähnliche Technologien auf iot-fabrikken.com (die "<strong>Website</strong>") verwendet. Sie ist zusammen mit unserer <a href="/de/legal/privacy/">Datenschutzerklärung</a> zu lesen.</p>
    <h2>Was sind Cookies?</h2>
    <p>Cookies sind kleine Textdateien auf Ihrem Gerät. Ähnliche Technologien umfassen Local Storage (Cookie-Einstellung) und Session Storage (kurzzeitige Attributierung während eines Besuchs).</p>
    <h2>Wie wir Cookies verwenden</h2>
    <p>Wir unterteilen Cookies in drei Kategorien. Optionale Kategorien können Sie über das Cookie-Banner oder "Cookie-Einstellungen" steuern.</p>
    <h3>Notwendig</h3>
    <p>Erforderlich, um Ihre Cookie-Auswahl zu speichern. Kein Tracking über Websites hinweg.</p>
    <ul><li><strong>Einwilligungspräferenz</strong> — speichert Ihre Auswahl (Local Storage, bis zu 12 Monate).</li></ul>
    <h3>Analyse (optional)</h3>
    <p>Hilft uns zu verstehen, wie Besucher die Website nutzen. Nur mit Einwilligung über Google Tag Manager, Google Analytics 4 (GA4) und Microsoft Clarity (Heatmaps und Session-Aufzeichnungen).</p>
    <ul>
      <li><strong>_ga, _ga_*</strong> — unterscheidet Nutzer und Sitzungen (bis zu 24 Monate).</li>
      <li><strong>_gid</strong> — unterscheidet Nutzer (24 Stunden).</li>
      <li><strong>_clck, _clsk, CLID, ANONCHK, MR, MUID, SM</strong> — Clarity-Sitzungs- und Heatmap-Kennungen (Microsoft, typisch bis zu 1 Jahr; Session-Aufzeichnung ist sampled).</li>
    </ul>
    <h3>Marketing (optional)</h3>
    <p>Misst Google-Ads-Kampagnen und unterstützt Remarketing, sofern zulässig. Nur mit Einwilligung.</p>
    <ul><li><strong>_gcl_*</strong> — Google-Ads-Konversions- und Klick-IDs (typisch 90 Tage).</li></ul>
    <h2>Rechtsgrundlage</h2>
    <p>Notwendige Speicherung basiert auf unserem berechtigten Interesse am Betrieb der Website. Analyse- und Marketing-Cookies werden nur nach Einwilligung gesetzt. Sie können die Einwilligung jederzeit über "Cookie-Einstellungen" widerrufen.</p>
    <h2>Verwaltung</h2>
    <p>Nutzen Sie das Cookie-Banner beim ersten Besuch oder <strong>Cookie-Einstellungen</strong> (unten links), um Ihre Wahl später zu ändern. Sie können Cookies auch im Browser blockieren.</p>
    <h2>Kontakt</h2>
    <p>Fragen zu Cookies: <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a>.</p>
    `,
  },
  impressum: {
    metaTitle: "Impressum | IoT Fabrikken",
    body: `
    <h3>Unternehmensangaben</h3>
    <p><strong>IoT Fabrikken ApS</strong><br />Brønsager 1<br />4000 Roskilde<br />Dänemark</p>
    <h3>Vertreten durch</h3>
    <p>Jon Wichmann (CEO / Partner)<br />Mikkel Fischer (Partner)</p>
    <h3>Kontakt</h3>
    <ul>
      <li><strong>Telefon:</strong> <a href="tel:+4571718090">+45 71 71 80 90</a></li>
      <li><strong>E-Mail:</strong> <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a></li>
      <li><strong>Website:</strong> <a href="https://www.iot-fabrikken.com/">www.iot-fabrikken.com</a></li>
    </ul>
    <h3>Registereintrag</h3>
    <p>Eingetragen bei der dänischen Wirtschaftsbehörde (<em>Det Centrale Virksomhedsregister</em>).</p>
    <p><strong>CVR-Nummer:</strong> 39110393</p>
    `,
  },
};

const sv: LegalDictionary = {
  common: { home: "Hem", legal: "Juridik", lastUpdated: "Senast uppdaterad:" },
  privacy: {
    metaTitle: "Integritetspolicy | IoT Fabrikken",
    lastUpdatedDate: "22 maj 2026",
    ctaTitle: "Frågor om dina data?",
    ctaSubtitle:
      "Kontakta oss, vi svarar på vardagar och kan hänvisa dig till rätt person för GDPR- eller produktspecifika förfrågningar.",
    body: `
    <p>Denna integritetspolicy beskriver hur IoT Fabrikken ApS ("<strong>IoT Fabrikken</strong>", "<strong>vi</strong>", "<strong>oss</strong>" eller "<strong>vår</strong>") samlar in, använder och delar personuppgifter när du använder vår webbplats, RoomAlyzer-plattformen och relaterade tjänster (tillsammans "<strong>Tjänsten</strong>"). Den förklarar också dina integritetsrättigheter och hur tillämplig lag skyddar dig.</p>
    <p>Vi använder personuppgifter för att tillhandahålla och förbättra Tjänsten. Genom att använda Tjänsten godkänner du insamling och användning av information i enlighet med denna integritetspolicy. När vi behandlar personuppgifter för en kunds räkning (till exempel sensoravläsningar och byggnadsdata i RoomAlyzer) agerar vi som <strong>personuppgiftsbiträde</strong> enligt kundens instruktioner; kundens integritetsmeddelande och personuppgiftsbiträdesavtal gäller för den behandlingen.</p>
    <h2>Tolkning och definitioner</h2>
    <h3>Tolkning</h3>
    <p>Ord med inledande stor bokstav har de betydelser som anges nedan. Samma betydelse gäller oavsett om de förekommer i singular eller plural.</p>
    <h3>Definitioner</h3>
    <p>I denna integritetspolicy gäller följande:</p>
    <ul>
      <li><strong>Konto</strong> avser ett unikt konto som skapats för dig för att få åtkomst till delar av Tjänsten.</li>
      <li><strong>Närstående bolag</strong> avser en enhet som kontrollerar, kontrolleras av eller står under gemensam kontroll med en part, där "kontroll" avser ägande av 50% eller mer av aktierna, kapitalandelarna eller andra värdepapper med rösträtt till val av styrelse eller annan ledning.</li>
      <li><strong>Applikation</strong> avser den RoomAlyzer-programvara som tillhandahålls av Företaget, inklusive webbapplikationen på app.roomalyzer.com och relaterade mobil- eller integrationsgränssnitt.</li>
      <li><strong>Företaget</strong> (benämnt "Företaget", "Vi", "Oss" eller "Vår") avser IoT Fabrikken ApS, Brønsager 1, 4000 Roskilde, Danmark (CVR 39 11 03 93).</li>
      <li><strong>Land</strong> avser Danmark.</li>
      <li><strong>Enhet</strong> avser varje enhet som kan få åtkomst till Tjänsten, såsom en dator, mobiltelefon eller surfplatta.</li>
      <li><strong>Personuppgifter</strong> avser all information som rör en identifierad eller identifierbar fysisk person.</li>
      <li><strong>Tjänst</strong> avser webbplatsen iot-fabrikken.com (och relaterade domäner), Applikationen, kundsupportportaler, demo- och kontaktflöden, nyhetsbrev och alla andra tjänster vi driver som länkar till denna policy.</li>
      <li><strong>Tjänsteleverantör</strong> avser en fysisk eller juridisk person som behandlar data för Företagets räkning för att underlätta Tjänsten, tillhandahålla Tjänsten på vår räkning, utföra tjänster relaterade till Tjänsten eller hjälpa oss att analysera hur Tjänsten används.</li>
      <li><strong>Användningsdata</strong> avser data som samlas in automatiskt, antingen genererad genom användning av Tjänsten eller från Tjänstens infrastruktur i sig (till exempel varaktigheten av ett sidbesök eller metadata för en API-förfrågan).</li>
      <li><strong>Du</strong> avser den person som får åtkomst till eller använder Tjänsten, eller det företag eller annan juridisk enhet på vars vägnar en sådan person får åtkomst till eller använder Tjänsten, beroende på vad som är tillämpligt.</li>
    </ul>
    <h2>Insamling och användning av dina personuppgifter</h2>
    <h3>Personuppgifter</h3>
    <p>När du använder vår Tjänst kan vi be dig att lämna personuppgifter som kan användas för att kontakta eller identifiera dig. Detta kan omfatta, men är inte begränsat till:</p>
    <ul>
      <li>E-postadress</li>
      <li>För- och efternamn</li>
      <li>Telefonnummer</li>
      <li>Företags- eller organisationsnamn och jobbtitel</li>
      <li>Adress, ort, region och postnummer (där det är relevant för beställningar eller avtal)</li>
      <li>Inloggningsuppgifter och profilinställningar</li>
      <li>Innehållet i de meddelanden du skickar oss (support, försäljning, demoförfrågningar)</li>
      <li>Användningsdata</li>
    </ul>
    <h3>Användningsdata</h3>
    <p>Användningsdata samlas in automatiskt när du använder Tjänsten.</p>
    <p>Användningsdata kan omfatta din Enhets internetprotokolladress (IP-adress), webbläsartyp och -version, de sidor du besöker, tidpunkten och datumet för ditt besök, den tid du spenderar på dessa sidor, unika enhetsidentifierare och andra diagnostiska data.</p>
    <p>När du får åtkomst till Tjänsten via en mobil enhet kan vi samla in information såsom typen av mobil enhet, unikt enhets-id, IP-adress, mobilt operativsystem, mobil webbläsartyp och andra diagnostiska data.</p>
    <p>Vi kan också samla in information som din webbläsare skickar när du besöker vår webbplats eller när du får åtkomst till Tjänsten via en mobil enhet. För cookies och liknande tekniker, se vår <a href="/sv/legal/cookies/">Cookiepolicy</a>.</p>
    <h3>Så använder vi dina personuppgifter</h3>
    <p>Företaget kan använda Personuppgifter för följande ändamål:</p>
    <ul>
      <li><strong>För att tillhandahålla och underhålla vår Tjänst</strong>, inklusive att övervaka användningen och driva Applikationen.</li>
      <li><strong>För att hantera ditt Konto</strong> och ge dig åtkomst till funktioner som är tillgängliga för registrerade användare.</li>
      <li><strong>För att fullgöra ett avtal</strong> avseende produkter eller tjänster du har köpt eller något annat avtal med oss via Tjänsten.</li>
      <li><strong>För att kontakta dig</strong> via e-post, telefon, SMS eller annan elektronisk kommunikation om uppdateringar, säkerhetsmeddelanden, support eller information om funktioner, produkter eller avtalade tjänster, där det är nödvändigt eller rimligt.</li>
      <li><strong>För att ge nyheter och erbjudanden</strong> om varor, tjänster och evenemang som liknar dem du har köpt eller frågat om, om du inte har avböjt.</li>
      <li><strong>För att hantera dina förfrågningar</strong> till oss (försäljning, support, demos, karriär).</li>
      <li><strong>Vid verksamhetsöverlåtelser</strong> såsom en fusion, avyttring, omstrukturering, omorganisation, upplösning eller försäljning av tillgångar, där Personuppgifter om Tjänstens användare kan ingå bland de överlåtna tillgångarna.</li>
      <li><strong>För andra ändamål</strong> såsom dataanalys, identifiering av användningstrender, mätning av kampanjers effektivitet och förbättring av vår Tjänst, våra produkter, tjänster, vår marknadsföring och din upplevelse.</li>
    </ul>
    <h3>Rättsliga grunder (EES och Storbritannien)</h3>
    <p>Där dataskyddsförordningen (GDPR) eller UK GDPR är tillämplig stödjer vi oss på en eller flera av följande rättsliga grunder: fullgörande av ett avtal, berättigade intressen (till exempel drift och säkring av Tjänsten, B2B-marknadsföring till befintliga kunder), fullgörande av en rättslig förpliktelse samt samtycke där det krävs (till exempel vissa cookies eller marknadsföringsregistreringar). Du kan när som helst återkalla ditt samtycke utan att det påverkar lagligheten av behandlingen före återkallelsen.</p>
    <h3>Delning av dina personuppgifter</h3>
    <p>Vi kan dela dina personuppgifter i följande situationer:</p>
    <ul>
      <li><strong>Med Tjänsteleverantörer</strong> som hjälper oss att driva Tjänsten, hosting, analys, e-postleverans, CRM, betalningshantering eller kundsupport, med förbehåll för lämpliga avtalsmässiga skyddsåtgärder.</li>
      <li><strong>Vid verksamhetsöverlåtelser</strong> i samband med eller under förhandlingar om en fusion, försäljning av Företagets tillgångar, finansiering eller förvärv.</li>
      <li><strong>Med Närstående bolag</strong>, som vi kräver ska efterleva denna integritetspolicy.</li>
      <li><strong>Med affärspartner</strong> för att erbjuda vissa produkter, tjänster eller kampanjer där du har valt att delta.</li>
      <li><strong>Med andra användare</strong> när du delar personuppgifter eller interagerar i offentliga delar av Tjänsten, där sådan information kan vara synlig för andra.</li>
      <li><strong>Med ditt samtycke</strong> för varje annat ändamål du har godkänt.</li>
      <li><strong>Med myndigheter</strong> där det krävs enligt lag eller för att skydda rättigheter, säkerhet och trygghet enligt beskrivningen nedan.</li>
    </ul>
    <p>En aktuell lista över underbiträden som används för RoomAlyzer-kunddata finns tillgänglig för kunder enligt våra <a href="/sv/legal/terms/">Villkor och personuppgiftsbiträdesavtal</a>.</p>
    <h2>Lagring av dina personuppgifter</h2>
    <p>Vi lagrar Personuppgifter endast så länge som det är nödvändigt för de ändamål som anges i denna integritetspolicy, inklusive för att uppfylla rättsliga förpliktelser, lösa tvister och göra avtal gällande.</p>
    <p>Användningsdata lagras i allmänhet under en kortare period, utom när de används för att stärka säkerheten eller förbättra funktionaliteten, eller där vi enligt lag är skyldiga att lagra dem längre.</p>
    <h2>Överföring av dina personuppgifter</h2>
    <p>Din information, inklusive Personuppgifter, behandlas på Företagets kontor och på andra platser där de parter som är involverade i behandlingen befinner sig. Data kan överföras till (och lagras på) system utanför ditt land där dataskyddslagstiftningen kan skilja sig åt.</p>
    <p>För kunddata i RoomAlyzer erbjuder vi som standard <strong>datalagring inom EU</strong>. Där överföringar utanför Europeiska ekonomiska samarbetsområdet sker använder vi lämpliga skyddsåtgärder såsom standardavtalsklausuler eller motsvarande mekanismer, om inte ett beslut om adekvat skyddsnivå gäller.</p>
    <p>Ditt samtycke till denna integritetspolicy följt av din inlämning av information utgör ditt godkännande av en sådan överföring där det är tillämpligt. Vi vidtar de åtgärder som rimligen är nödvändiga för att säkerställa att dina data behandlas säkert och i enlighet med denna integritetspolicy.</p>
    <h2>Utlämnande av dina personuppgifter</h2>
    <h3>Affärstransaktioner</h3>
    <p>Om Företaget är involverat i en fusion, ett förvärv eller en försäljning av tillgångar kan dina Personuppgifter överföras. Vi lämnar besked innan dina Personuppgifter överförs och omfattas av en annan integritetspolicy.</p>
    <h3>Brottsbekämpning och andra rättsliga krav</h3>
    <p>Under vissa omständigheter kan Företaget vara skyldigt att lämna ut dina Personuppgifter om det krävs enligt lag eller som svar på giltiga förfrågningar från offentliga myndigheter (till exempel en domstol eller en myndighet). Vi kan lämna ut Personuppgifter när vi i god tro anser att utlämnande är nödvändigt för att:</p>
    <ul>
      <li>Uppfylla en rättslig förpliktelse</li>
      <li>Skydda och försvara Företagets rättigheter eller egendom</li>
      <li>Förhindra eller utreda möjliga oegentligheter i samband med Tjänsten</li>
      <li>Skydda den personliga säkerheten för Tjänstens användare eller allmänheten</li>
      <li>Skydda mot rättsligt ansvar</li>
    </ul>
    <h2>Säkerhet för dina personuppgifter</h2>
    <p>Säkerheten för dina Personuppgifter är viktig för oss. Vi använder kommersiellt acceptabla tekniska och organisatoriska åtgärder, inklusive kryptering under överföring och i vila för Applikationen, åtkomstkontroller och regelbunden säkerhetstestning. Ingen metod för överföring via internet eller elektronisk lagring är 100% säker; vi kan inte garantera absolut säkerhet. Ytterligare detaljer finns på vår <a href="/sv/legal/security/">Säkerhet</a>-sida och i kunddokumentationen.</p>
    <h2>Dina integritetsrättigheter</h2>
    <p>Beroende på var du bor kan du ha rätt till åtkomst, rättelse, radering, begränsning av eller invändning mot behandling, dataportabilitet och att lämna in ett klagomål till en tillsynsmyndighet. Om du är slutanvändare av en kunds RoomAlyzer-driftsättning, kontakta först den kunden; vi bistår våra kunder med att besvara förfrågningar från registrerade i egenskap av personuppgiftsbiträde.</p>
    <p>För att utöva rättigheter avseende data som vi kontrollerar direkt (till exempel webbkonton, marknadsförings- eller försäljningsförfrågningar), kontakta oss via uppgifterna nedan. Vi kan behöva verifiera din identitet innan vi svarar.</p>
    <h2>Barns integritet</h2>
    <p>Vår Tjänst vänder sig inte till någon under 13 år. Vi samlar inte medvetet in personligt identifierbar information från någon under 13 år. Om du är förälder eller vårdnadshavare och tror att ditt barn har lämnat oss Personuppgifter, kontakta oss. Om vi blir medvetna om att vi har samlat in Personuppgifter från någon under 13 år utan verifiering av föräldrars samtycke, vidtar vi åtgärder för att ta bort den informationen från våra servrar.</p>
    <p>Där vi stödjer oss på samtycke som rättslig grund och ditt land kräver samtycke från en förälder, kan vi kräva föräldrars samtycke innan vi samlar in och använder den informationen.</p>
    <h2>Länkar till andra webbplatser</h2>
    <p>Vår Tjänst kan innehålla länkar till webbplatser som inte drivs av oss. Om du klickar på en tredjepartslänk dirigeras du till den tredje partens webbplats. Vi rekommenderar starkt att du granskar integritetspolicyn för varje webbplats du besöker. Vi har ingen kontroll över och tar inget ansvar för innehållet, integritetspolicyerna eller praxis på tredje parts webbplatser eller tjänster.</p>
    <h2>Ändringar av denna integritetspolicy</h2>
    <p>Vi kan uppdatera denna integritetspolicy då och då. Vi meddelar dig om väsentliga ändringar genom att publicera den nya integritetspolicyn på denna sida och uppdatera datumet för "Senast uppdaterad". Där det är lämpligt kan vi även meddela dig via e-post eller genom ett tydligt meddelande i Tjänsten innan ändringarna träder i kraft.</p>
    <p>Vi rekommenderar att du granskar denna integritetspolicy regelbundet. Ändringar träder i kraft när de publiceras på denna sida.</p>
    <h2>Kontakta oss</h2>
    <p>Om du har frågor om denna integritetspolicy eller vår användning av dina personuppgifter, kontakta oss:</p>
    <ul>
      <li><strong>E-post:</strong> <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a> (allmänna förfrågningar och integritet)</li>
      <li><strong>Produktsupport:</strong> <a href="mailto:support@iot-fabrikken.com">support@iot-fabrikken.com</a></li>
      <li><strong>Telefon:</strong> <a href="tel:+4571718090">+45 71 71 80 90</a></li>
      <li><strong>Post:</strong> IoT Fabrikken ApS, Brønsager 1, 4000 Roskilde, Danmark</li>
    </ul>
    `,
  },
  cookies: {
    metaTitle: "Cookiepolicy | IoT Fabrikken",
    lastUpdatedDate: "7 juli 2026",
    ctaTitle: "Frågor om cookies eller mätning?",
    ctaSubtitle:
      "Kontakta oss om du behöver hjälp att ändra dina inställningar eller vill veta mer om hur vi mäter kampanjer.",
    body: `
    <p>Denna cookiepolicy beskriver hur IoT Fabrikken ApS ("<strong>vi</strong>") använder cookies och liknande tekniker på iot-fabrikken.com ("<strong>webbplatsen</strong>"). Den bör läsas tillsammans med vår <a href="/sv/legal/privacy/">Integritetspolicy</a>.</p>
    <h2>Vad är cookies?</h2>
    <p>Cookies är små textfiler som lagras på din enhet när du besöker en webbplats. Liknande tekniker inkluderar local storage (cookieval) och session storage (kortvarig attributering under ett besök).</p>
    <h2>Hur vi använder cookies</h2>
    <p>Vi delar in cookies i tre kategorier. Du kan acceptera eller avvisa valfria kategorier via cookiebannern eller "Cookieinställningar".</p>
    <h3>Nödvändiga</h3>
    <p>Krävs för att komma ihåg ditt cookieval. De spårar dig inte mellan webbplatser.</p>
    <ul><li><strong>Samtyckesinställning</strong> — lagrar ditt val (local storage, upp till 12 månader).</li></ul>
    <h3>Analys (valfritt)</h3>
    <p>Hjälper oss att förstå hur besökare använder webbplatsen. Laddas endast med samtycke via Google Tag Manager, Google Analytics 4 (GA4) och Microsoft Clarity (heatmaps och sessioninspelningar).</p>
    <ul>
      <li><strong>_ga, _ga_*</strong> — skiljer användare och sessioner (upp till 24 månader).</li>
      <li><strong>_gid</strong> — skiljer användare (24 timmar).</li>
      <li><strong>_clck, _clsk, CLID, ANONCHK, MR, MUID, SM</strong> — Clarity-session och heatmap-id (Microsoft, typiskt upp till 1 år; sessioninspelning är sampled).</li>
    </ul>
    <h3>Marknadsföring (valfritt)</h3>
    <p>Mäter Google Ads-kampanjer och stödjer remarketing där det är tillåtet. Laddas endast med samtycke.</p>
    <ul><li><strong>_gcl_*</strong> — Google Ads-konverterings- och klick-id (typiskt 90 dagar).</li></ul>
    <h2>Rättslig grund</h2>
    <p>Nödvändig lagring bygger på vårt berättigade intresse av att driva webbplatsen. Analys- och marknadsföringscookies sätts endast efter samtycke. Du kan när som helst återkalla samtycket via "Cookieinställningar".</p>
    <h2>Hantering</h2>
    <p>Använd cookiebannern vid första besöket, eller klicka på <strong>Cookieinställningar</strong> (nederst till vänster) för att ändra valet senare. Du kan också blockera cookies i webbläsaren.</p>
    <h2>Kontakt</h2>
    <p>Frågor om cookies: <a href="mailto:info@iot-fabrikken.com">info@iot-fabrikken.com</a>.</p>
    `,
  },
};

const dictionaries: Record<Lang, LegalDictionary> = { en, da, de, sv };

function applyLocaleLegalLinks(html: string, lang: Lang): string {
  // The inline bodies hard-code locale-prefixed English-segment legal links
  // (`/de/legal/security/`, …). Rewrite every locale variant to the localized
  // route (`/de/rechtliches/security/`) so they resolve in one hop.
  return html.replace(
    /href="\/(?:en|da|de|sv)\/legal\/(cookies|terms|security)\/"/g,
    (_match, slug) => `href="${langPath(`legal/${slug}`, lang)}"`,
  );
}

export function getLegal(lang: Lang): LegalStrings {
  const base = dictionaries[lang] ?? dictionaries[defaultLang];
  const impressum = base.impressum ?? dictionaries.en.impressum!;
  const privacyBody = applyLocaleLegalLinks(
    applyLocaleContactToHtml(base.privacy.body, lang),
    lang,
  );
  const cookiesBody = applyLocaleLegalLinks(
    applyLocaleContactToHtml(base.cookies.body, lang),
    lang,
  );
  return {
    ...base,
    privacy: {
      ...base.privacy,
      body: privacyBody,
    },
    cookies: {
      ...base.cookies,
      body: cookiesBody,
    },
    impressum: {
      ...impressum,
      body: applyLocaleContactToHtml(impressum.body, lang),
    },
  };
}
