/** Generated by scripts/calibrate-dimension-brackets.mjs — do not edit. */
export type DimensionBracketSlot = "h" | "w" | "static";

export type DimensionBracketCoords = { x: number; y: number };

export const dimensionBracketCalibration = {
  "co2-dimensions.webp": {
    "h": {
      "x": 72.78,
      "y": 36.3
    },
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "humidity-dimensions.webp": {
    "h": {
      "x": 63.15,
      "y": 38.98
    },
    "w": {
      "x": 49.95,
      "y": 63.01
    }
  },
  "cloud-connector-dimensions.webp": {
    "h": {
      "x": 72.78,
      "y": 36.3
    },
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "touch-dimensions.webp": {
    "h": {
      "x": 63.33,
      "y": 36.3
    },
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "motion-dimensions.webp": {
    "h": {
      "x": 60.65,
      "y": 36.2
    },
    "w": {
      "x": 49.95,
      "y": 64.44
    }
  },
  "mini-plus-pir-dimensions.webp": {
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "open-close-dimensions-compact.webp": {
    "h": {
      "x": 63.15,
      "y": 42.87
    },
    "w": {
      "x": 49.95,
      "y": 63.01
    }
  },
  "open-close-dimensions-pro.webp": {
    "h": {
      "x": 63.15,
      "y": 38.98
    },
    "w": {
      "x": 49.95,
      "y": 63.01
    }
  },
  "outdoor-dimensions.webp": {
    "h": {
      "x": 72.78,
      "y": 36.3
    },
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "mini-plus-dimensions.webp": {
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "full-plus-dimensions.webp": {
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "temperature-dimensions.webp": {
    "w": {
      "x": 54.54,
      "y": 61.34
    }
  },
  "desk-dimensions.webp": {
    "w": {
      "x": 54.54,
      "y": 61.34
    }
  },
  "water-detector-dimensions-compact.webp": {
    "h": {
      "x": 72.78,
      "y": 36.3
    },
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "water-rope-dimensions-compact.webp": {
    "h": {
      "x": 72.78,
      "y": 36.3
    },
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "water-detector-dimensions-pro.webp": {
    "h": {
      "x": 72.78,
      "y": 36.3
    },
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "water-rope-dimensions-pro.webp": {
    "h": {
      "x": 72.78,
      "y": 36.3
    },
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "range-extender-dimensions.webp": {
    "w": {
      "x": 49.95,
      "y": 64.49
    }
  },
  "bracket-dimensions.webp": {
    "h": {
      "x": 63.33,
      "y": 36.2
    },
    "w": {
      "x": 49.95,
      "y": 64.44
    }
  }
} as const satisfies Record<
  string,
  Partial<Record<DimensionBracketSlot, DimensionBracketCoords>>
>;
