/**
 * Label placement for dimension photos with baked-in bracket guides.
 * Side-view presets use `slot` keys resolved from dimensionBracketCalibration.ts
 * (generated by scripts/calibrate-dimension-brackets.mjs).
 */
import type { DimensionAxis } from "../lib/sensors/parse-dimensions";

export type DimensionBracketSlotKey = "h" | "w";

export type DimensionAxisLabelSlot = {
  axis: DimensionAxis;
  /** Look up x/y from dimensionBracketCalibration by image basename. */
  slot?: DimensionBracketSlotKey;
  /** Fallback when no calibration entry exists. */
  x?: number;
  y?: number;
  /** Nudge in viewBox units (negative = up). */
  dy?: number;
  textAnchor?: "start" | "middle" | "end";
  dominantBaseline?: "middle" | "hanging" | "auto";
};

export type DimensionStaticLabelSlot = {
  text: string;
  x: number;
  y: number;
  /** Nudge in viewBox units (negative = up). */
  dy?: number;
  textAnchor?: "start" | "middle" | "end";
  dominantBaseline?: "middle" | "hanging" | "auto";
};

export type DimensionLabelSlot = DimensionAxisLabelSlot | DimensionStaticLabelSlot;

export type DimensionOverlayPreset = {
  labels: DimensionLabelSlot[];
};

export const dimensionOverlayPresets = {
  /** Standard side-view layout — calibration per WebP basename. */
  bracketSide: {
    labels: [
      { axis: "w", slot: "w", textAnchor: "middle", dominantBaseline: "middle" },
      { axis: "h", slot: "h", textAnchor: "middle", dominantBaseline: "middle" },
    ],
  },
  /** Open/Close small and large units — same bracket geometry, different images. */
  bracketSideOpenClose: {
    labels: [
      { axis: "w", slot: "w", textAnchor: "middle", dominantBaseline: "middle" },
      { axis: "h", slot: "h", textAnchor: "middle", dominantBaseline: "middle" },
    ],
  },
  /** Water detector / Water rope — Compact (IP30). */
  bracketSideWaterCompact: {
    labels: [
      { axis: "w", slot: "w", textAnchor: "middle", dominantBaseline: "middle" },
      { axis: "h", slot: "h", textAnchor: "middle", dominantBaseline: "middle" },
      { text: "IP 30", x: 50, y: 20, textAnchor: "middle", dominantBaseline: "middle" },
    ],
  },
  /** Water detector / Water rope — Pro (IP67). */
  bracketSideWaterPro: {
    labels: [
      { axis: "w", slot: "w", textAnchor: "middle", dominantBaseline: "middle" },
      { axis: "h", slot: "h", textAnchor: "middle", dominantBaseline: "middle" },
      { text: "IP 67", x: 50, y: 20, textAnchor: "middle", dominantBaseline: "middle" },
    ],
  },
  /** Temperature, Desk — isometric coin (explicit coords; not slot-calibrated). */
  bracketIsometric: {
    labels: [
      { axis: "w", x: 36.3, y: 64.6, textAnchor: "middle", dominantBaseline: "middle" },
      { axis: "h", x: 75.2, y: 51, textAnchor: "middle", dominantBaseline: "middle" },
    ],
  },
} as const satisfies Record<string, DimensionOverlayPreset>;

export type DimensionOverlayPresetKey = keyof typeof dimensionOverlayPresets;
