/**
 * Optimised homepage hero image URLs.
 * Generated by `scripts/optimize-hero-images.mjs`.
 */
import manifest from "./heroImages.json";

export type HeroBackdropImage = {
  src: string;
  width: number;
  height: number;
  srcSet: { width: number; url: string }[];
};

export type HeroManImage = {
  src: string;
  width: number;
  height: number;
};

export const heroBackdropImage: HeroBackdropImage = manifest.backdrop;
export const heroManImage: HeroManImage = manifest.man;
