/**
 * Card images for the homepage sensor-finder section.
 * Width variants are generated by `scripts/optimize-sensor-finder-images.mjs`.
 */
import manifest from "./sensorFinderImages.json";

export type SensorFinderCardImage = {
  image: string;
  width: number;
  height: number;
  srcSet: { width: number; url: string }[];
};

export const sensorFinderCardImages: Record<string, SensorFinderCardImage> = manifest;

export function getSensorFinderCardImage(slug: string): SensorFinderCardImage | undefined {
  return sensorFinderCardImages[slug];
}
